<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250911094658 extends AbstractMigration
{
    private function isPostgreSql(): bool
    {
        return $this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform;
    }

    private function qi(string $identifier): string
    {
        return $this->connection->quoteIdentifier($identifier);
    }

    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        if (true === $this->isPostgreSql()) {
            $userTable = $this->qi('user');
            $dateColumn = $this->qi('date');

            $this->addSql(sprintf(
                'CREATE TABLE game (game_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, type INT DEFAULT NULL, winner VARCHAR(255) DEFAULT NULL, %s DATE NOT NULL, status SMALLINT DEFAULT NULL, round INT DEFAULT NULL, PRIMARY KEY(game_id))',
                $dateColumn,
            ));
            $this->addSql('CREATE TABLE game_players (game_player_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, player_id INT NOT NULL, position INT NOT NULL, score INT NOT NULL, PRIMARY KEY(game_player_id))');
            $this->addSql('CREATE TABLE player_stats (player_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, wins INT DEFAULT NULL, win_percentage INT NOT NULL, round_average INT DEFAULT NULL, highest_checkout INT DEFAULT NULL, games_played INT DEFAULT NULL, PRIMARY KEY(player_id))');
            $this->addSql('CREATE TABLE round (round_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, round_number INT NOT NULL, PRIMARY KEY(round_id))');
            $this->addSql('CREATE TABLE round_throws (throw_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, game_id INT NOT NULL, round_id INT NOT NULL, player_id INT NOT NULL, throw_number INT NOT NULL, value INT NOT NULL, is_bust BOOLEAN NOT NULL, is_double BOOLEAN NOT NULL, is_triple BOOLEAN DEFAULT NULL, score INT NOT NULL, PRIMARY KEY(throw_id))');
            $this->addSql(sprintf('CREATE TABLE %s (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))', $userTable));
            $this->addSql(sprintf('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON %s (email)', $userTable));
            $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
            $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
            $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
            $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
            $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
            $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
            $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');

            return;
        }

        $this->addSql('CREATE TABLE game (game_id INT AUTO_INCREMENT NOT NULL, type INT DEFAULT NULL, winner VARCHAR(255) DEFAULT NULL, date DATE NOT NULL, status TINYINT(1) DEFAULT NULL, round INT DEFAULT NULL, PRIMARY KEY(game_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE game_players (game_player_id INT AUTO_INCREMENT NOT NULL, game_id INT NOT NULL, player_id INT NOT NULL, position INT NOT NULL, score INT NOT NULL, PRIMARY KEY(game_player_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE player_stats (player_id INT AUTO_INCREMENT NOT NULL, wins INT DEFAULT NULL, win_percentage INT NOT NULL, round_average INT DEFAULT NULL, highest_checkout INT DEFAULT NULL, games_played INT DEFAULT NULL, PRIMARY KEY(player_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE round (round_id INT AUTO_INCREMENT NOT NULL, game_id INT NOT NULL, round_number INT NOT NULL, PRIMARY KEY(round_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE round_throws (throw_id INT AUTO_INCREMENT NOT NULL, game_id INT NOT NULL, round_id INT NOT NULL, player_id INT NOT NULL, throw_number INT NOT NULL, value INT NOT NULL, is_bust TINYINT(1) NOT NULL, is_double TINYINT(1) NOT NULL, is_triple TINYINT(1) DEFAULT NULL, score INT NOT NULL, PRIMARY KEY(throw_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        if (true === $this->isPostgreSql()) {
            $this->addSql('DROP TABLE game');
            $this->addSql('DROP TABLE game_players');
            $this->addSql('DROP TABLE player_stats');
            $this->addSql('DROP TABLE round');
            $this->addSql('DROP TABLE round_throws');
            $this->addSql(sprintf('DROP TABLE %s', $this->qi('user')));
            $this->addSql('DROP TABLE messenger_messages');

            return;
        }

        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE game_players');
        $this->addSql('DROP TABLE player_stats');
        $this->addSql('DROP TABLE round');
        $this->addSql('DROP TABLE round_throws');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
