<?php
/**
 * This file is part of the darts backend.
 *
 * @license Proprietary
 */

declare(strict_types=1);

namespace App\Repository;

use App\Entity\GamePlayers;
use Doctrine\DBAL\ParameterType;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<GamePlayers>
 * This class was generated by the Doctrine ORM. Add your own custom
 */
final class GamePlayersRepository extends ServiceEntityRepository implements GamePlayersRepositoryInterface
{
    /**
     * @param ManagerRegistry $registry
     *
     * @psalm-suppress PossiblyUnusedMethod
     * @psalm-suppress UnusedParam
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, GamePlayers::class);
    }

    /**
     * Find players with user information for a specific game
     * @param int $gameId
     *
     * @return array
     */
    public function findPlayersWithUserInfo(int $gameId): array
    {
        $players = $this->createQueryBuilder('gamePlayer')
            ->select(
                'u.id as id',
                'gamePlayer.displayNameSnapshot as name',
                'gamePlayer.position as position',
                'u.isGuest as isGuest'
            )
            ->innerJoin('gamePlayer.player', 'u')
            ->andWhere('gamePlayer.game = :gameId')
            ->setParameter('gameId', $gameId)
            ->orderBy('gamePlayer.position', 'ASC')
            ->addOrderBy('u.id', 'ASC')
            ->getQuery()
            ->getArrayResult();

        return array_map(static function (array $player): array {
            return [
                'id' => isset($player['id']) ? (int) $player['id'] : null,
                'name' => $player['name'] ?? null,
                'position' => isset($player['position']) ? (int) $player['position'] : null,
                'isGuest' => isset($player['isGuest']) ? (bool) $player['isGuest'] : false,
            ];
        }, $players);
    }

    /**
     * Check if a player already joined the game
     * @param int $gameId
     * @param int $playerId
     *
     * @return bool
     */
    public function isPlayerInGame(int $gameId, int $playerId): bool
    {
        $count = $this->count([
            'game' => $gameId,
            'player' => $playerId,
        ]);

        return $count > 0;
    }

    /**
     * @return GamePlayers[]
     *
     * @param int $gameId
     */
    public function findByGameId(int $gameId): array
    {
        return $this->createQueryBuilder('gp')
            ->addSelect('player')
            ->innerJoin('gp.player', 'player')
            ->andWhere('gp.game = :gameId')
            ->setParameter('gameId', $gameId)
            ->orderBy('gp.position', 'ASC')
            ->addOrderBy('gp.gamePlayerId', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param int    $gameId
     * @param string $name
     *
     * @return bool
     */
    public function existsNameInGame(int $gameId, string $name): bool
    {
        $normalizedName = trim($name);
        $normalizedName = function_exists('mb_strtolower')
            ? mb_strtolower($normalizedName)
            : strtolower($normalizedName);

        if ('' === $normalizedName) {
            return false;
        }

        $connection = $this->getEntityManager()->getConnection();
        $userTable = $connection->getDatabasePlatform()->quoteIdentifier('user');

        $result = $connection->fetchOne(
            sprintf(
                <<<'SQL'
SELECT 1
FROM game_players gp
INNER JOIN %s u ON u.id = gp.player_id
WHERE gp.game_id = :gameId
    AND LOWER(
        TRIM(
            COALESCE(
                NULLIF(TRIM(gp.display_name_snapshot), ''),
                NULLIF(TRIM(u.display_name), ''),
                TRIM(u.username)
            )
        )
    ) = :name
LIMIT 1
SQL,
                $userTable,
            ),
            [
                'gameId' => $gameId,
                'name' => $normalizedName,
            ],
            [
                'gameId' => ParameterType::INTEGER,
                'name' => ParameterType::STRING,
            ]
        );

        return false !== $result;
    }

    /**
     * @param int $gameId
     *
     * @return int
     */
    public function findNextPositionForGame(int $gameId): int
    {
        $row = $this->getEntityManager()->getConnection()->fetchAssociative(
            <<<'SQL'
SELECT
    MAX(gp.position) AS maxPosition,
    COUNT(gp.game_player_id) AS playersCount
FROM game_players gp
WHERE gp.game_id = :gameId
SQL,
            ['gameId' => $gameId],
            ['gameId' => ParameterType::INTEGER]
        );

        $maxPosition = $row['maxPosition'] ?? null;
        if (null !== $maxPosition) {
            return (int) $maxPosition + 1;
        }

        return (int) ($row['playersCount'] ?? 0) + 1;
    }

    /**
     * @param int $gameId
     *
     * @return array<int, array{playerId:int,name:string,position:int|null,score:int|null,isGuest:bool}>
     */
    public function findGameStatePlayersByGameId(int $gameId): array
    {
        $rows = $this->createQueryBuilder('gp')
            ->select(
                'player.id AS playerId',
                "CASE
                    WHEN gp.displayNameSnapshot IS NOT NULL AND gp.displayNameSnapshot <> '' THEN gp.displayNameSnapshot
                    WHEN player.displayName IS NOT NULL AND player.displayName <> '' THEN player.displayName
                    ELSE player.username
                END AS name",
                'gp.position AS position',
                'gp.score AS score',
                'player.isGuest AS isGuest'
            )
            ->innerJoin('gp.player', 'player')
            ->andWhere('gp.game = :gameId')
            ->setParameter('gameId', $gameId)
            ->orderBy('gp.position', 'ASC')
            ->addOrderBy('gp.gamePlayerId', 'ASC')
            ->getQuery()
            ->getArrayResult();

        return array_map(static function (array $row): array {
            return [
                'playerId' => (int) $row['playerId'],
                'name' => (string) $row['name'],
                'position' => isset($row['position']) ? (int) $row['position'] : null,
                'score' => isset($row['score']) ? (int) $row['score'] : null,
                'isGuest' => isset($row['isGuest']) ? (bool) $row['isGuest'] : false,
            ];
        }, $rows);
    }

    /**
     * Counts how many players in a game have already finished (score == 0).
     *
     * @param int $gameId
     *
     * @return int
     */
    public function countFinishedPlayers(int $gameId): int
    {
        return (int) $this->createQueryBuilder('gp')
            ->select('COUNT(gp.gamePlayerId)')
            ->andWhere('gp.game = :gameId')
            ->andWhere('gp.score = 0')
            ->setParameter('gameId', $gameId)
            ->getQuery()
            ->getSingleScalarResult();
    }



    //    /**
    //     * @return GamePlayers[] Returns an array of GamePlayers objects
    //     */
    //    public function findByExampleField($value): array
    //    {
    //        return $this->createQueryBuilder('g')
    //            ->andWhere('g.exampleField = :val')
    //            ->setParameter('val', $value)
    //            ->orderBy('g.id', 'ASC')
    //            ->setMaxResults(10)
    //            ->getQuery()
    //            ->getResult()
    //        ;
    //    }

    //    public function findOneBySomeField($value): ?GamePlayers
    //    {
    //        return $this->createQueryBuilder('g')
    //            ->andWhere('g.exampleField = :val')
    //            ->setParameter('val', $value)
    //            ->getQuery()
    //            ->getOneOrNullResult()
    //        ;
    //    }
}
