<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Game;
use App\Enum\GameStatus;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<Game>
 * This class was generated by the Doctrine ORM. Add your own custom
 */
final class GameRepository extends ServiceEntityRepository
{
    /**
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Game::class);
    }

    //    /**
    //     * @return Game[] Returns an array of Game objects
    //     */
    //    public function findByExampleField($value): array
    //    {
    //        return $this->createQueryBuilder('g')
    //            ->andWhere('g.exampleField = :val')
    //            ->setParameter('val', $value)
    //            ->orderBy('g.id', 'ASC')
    //            ->setMaxResults(10)
    //            ->getQuery()
    //            ->getResult()
    //        ;
    //    }

    /**
     * @param int $gameId
     *
     * @return Game|null
     */
    public function findOneByGameId(int $gameId): ?Game
    {
        return $this->createQueryBuilder('g')
            ->andWhere('g.gameId = :gameId')
            ->setParameter('gameId', $gameId)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @return int|null
     */
    public function findHighestGameId(): ?int
    {
        $result = $this->createQueryBuilder('g')
            ->select('MAX(g.gameId)')
            ->getQuery()
            ->getSingleScalarResult();

        return $result ? (int) $result : null;
    }

    /**
     * @return int
     */
    public function countFinishedGames(): int
    {
        return (int) $this->createQueryBuilder('g')
            ->select('COUNT(g.gameId)')
            ->andWhere('g.status = :status')
            ->setParameter('status', GameStatus::Finished)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
