<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Game;
use App\Enum\GameStatus;
use App\Util\SqlResultValueAccessor;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\DBAL\LockMode;
use Doctrine\DBAL\ArrayParameterType;
use Doctrine\DBAL\ParameterType;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @extends ServiceEntityRepository<Game>
 * This class was generated by the Doctrine ORM. Add your own custom
 */
final class GameRepository extends ServiceEntityRepository implements GameRepositoryInterface
{
    /**
     * @param ManagerRegistry $registry
     *
     * @psalm-suppress PossiblyUnusedMethod
     * @psalm-suppress UnusedParam
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Game::class);
    }

    /**
     * @param int $limit
     * @param int $offset
     *
     * @return list<array{
     *     id:int,
     *     date:string|null,
     *     finishedAt:string|null,
     *     playersCount:int,
     *     winnerName:string|null,
     *     winnerId:int|null,
     *     winnerRounds:int
     * }>
     */
    #[\Override]
    public function findFinishedOverview(int $limit, int $offset): array
    {
        $connection = $this->getEntityManager()->getConnection();
        $userTable = $connection->getDatabasePlatform()->quoteSingleIdentifier('user');
        $rows = $connection->fetchAllAssociative(
            sprintf(
                <<<'SQL'
SELECT
    g.game_id AS id,
    g.date AS date,
    g.finished_at AS finishedAt,
    COUNT(DISTINCT gp.game_player_id) AS playersCount,
    winner.id AS winnerId,
    CASE
        WHEN winner_gp.display_name_snapshot IS NOT NULL AND winner_gp.display_name_snapshot <> '' THEN winner_gp.display_name_snapshot
        WHEN winner.display_name IS NOT NULL AND winner.display_name <> '' THEN winner.display_name
        ELSE winner.username
    END AS winnerName
FROM game g
LEFT JOIN game_players gp ON gp.game_id = g.game_id
LEFT JOIN %s winner ON winner.id = g.winner_id
LEFT JOIN game_players winner_gp ON winner_gp.game_id = g.game_id AND winner_gp.player_id = g.winner_id
WHERE g.status = :status
GROUP BY g.game_id, g.date, g.finished_at, winner.id, winner.display_name, winner.username, winner_gp.display_name_snapshot
ORDER BY g.game_id DESC
LIMIT :limit OFFSET :offset
SQL,
                $userTable,
            ),
            [
                'status' => GameStatus::Finished->value,
                'limit' => $limit,
                'offset' => $offset,
            ],
            [
                'status' => ParameterType::STRING,
                'limit' => ParameterType::INTEGER,
                'offset' => ParameterType::INTEGER,
            ]
        );

        if ([] === $rows) {
            return [];
        }

        $winnerRoundsByGameId = $this->findWinnerRoundsByGameIds(array_map(
            static fn(array $row): int => (int) $row['id'],
            $rows
        ));

        return array_map(function (array $row) use ($winnerRoundsByGameId): array {
            $gameId = (int) (SqlResultValueAccessor::find($row, ['id']) ?? 0);
            $winnerId = SqlResultValueAccessor::find($row, ['winnerId']);
            $winnerName = SqlResultValueAccessor::find($row, ['winnerName']);

            return [
                'id' => $gameId,
                'date' => $this->formatDateTimeValue(SqlResultValueAccessor::find($row, ['date'])),
                'finishedAt' => $this->formatDateTimeValue(SqlResultValueAccessor::find($row, ['finishedAt'])),
                'playersCount' => (int) (SqlResultValueAccessor::find($row, ['playersCount']) ?? 0),
                'winnerName' => null !== $winnerName ? (string) $winnerName : null,
                'winnerId' => null !== $winnerId ? (int) $winnerId : null,
                'winnerRounds' => $winnerRoundsByGameId[$gameId] ?? 0,
            ];
        }, $rows);
    }

    //    /**
    //     * @return Game[] Returns an array of Game objects
    //     */
    //    public function findByExampleField($value): array
    //    {
    //        return $this->createQueryBuilder('g')
    //            ->andWhere('g.exampleField = :val')
    //            ->setParameter('val', $value)
    //            ->orderBy('g.id', 'ASC')
    //            ->setMaxResults(10)
    //            ->getQuery()
    //            ->getResult()
    //        ;
    //    }

    /**
     * @param int $gameId
     *
     * @return Game|null
     */
    #[\Override]
    public function findOneByGameId(int $gameId): ?Game
    {
        return $this->createQueryBuilder('g')
            ->andWhere('g.gameId = :gameId')
            ->setParameter('gameId', $gameId)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * @param int $gameId
     *
     * @return Game|null
     */
    #[\Override]
    public function findOneByGameIdForUpdate(int $gameId): ?Game
    {
        return $this->createQueryBuilder('g')
            ->andWhere('g.gameId = :gameId')
            ->setParameter('gameId', $gameId)
            ->getQuery()
            ->setLockMode(LockMode::PESSIMISTIC_WRITE)
            ->getOneOrNullResult();
    }

    /**
     * @return int|null
     */
    #[\Override]
    public function findHighestGameId(): ?int
    {
        $result = $this->createQueryBuilder('g')
            ->select('MAX(g.gameId)')
            ->getQuery()
            ->getSingleScalarResult();

        return $result ? (int) $result : null;
    }

    /**
     * @return int
     */
    #[\Override]
    public function countFinishedGames(): int
    {
        return (int) $this->createQueryBuilder('g')
            ->select('COUNT(g.gameId)')
            ->andWhere('g.status = :status')
            ->setParameter('status', GameStatus::Finished)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param int $limit
     * @param int $offset
     *
     * @return Game[]
     */
    #[\Override]
    public function findFinished(int $limit, int $offset): array
    {
        return $this->createQueryBuilder('g')
            ->andWhere('g.status = :status')
            ->setParameter('status', GameStatus::Finished)
            ->orderBy('g.gameId', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param list<int> $gameIds
     *
     * @return array<int, int>
     */
    private function findWinnerRoundsByGameIds(array $gameIds): array
    {
        $uniqueGameIds = array_values(array_unique($gameIds));
        if ([] === $uniqueGameIds) {
            return [];
        }

        $connection = $this->getEntityManager()->getConnection();
        $roundTable = $connection->getDatabasePlatform()->quoteSingleIdentifier('round');

        $rows = $connection->fetchAllAssociative(
            sprintf(
                <<<'SQL'
SELECT
    rt.game_id AS gameId,
    COUNT(DISTINCT r.round_number) AS winnerRounds
FROM round_throws rt
INNER JOIN %s r ON r.round_id = rt.round_id
INNER JOIN game g ON g.game_id = rt.game_id AND g.winner_id = rt.player_id
WHERE rt.game_id IN (:gameIds)
GROUP BY rt.game_id
SQL,
                $roundTable,
            ),
            ['gameIds' => $uniqueGameIds],
            ['gameIds' => ArrayParameterType::INTEGER]
        );

        $winnerRoundsByGameId = [];
        foreach ($rows as $row) {
            $gameId = (int) (SqlResultValueAccessor::find($row, ['gameId']) ?? 0);
            if ($gameId <= 0) {
                continue;
            }

            $winnerRoundsByGameId[$gameId] = (int) (SqlResultValueAccessor::find($row, ['winnerRounds']) ?? 0);
        }

        return $winnerRoundsByGameId;
    }

    /**
     * @param mixed $value
     *
     * @return string|null
     */
    private function formatDateTimeValue(mixed $value): ?string
    {
        if ($value instanceof DateTimeInterface) {
            return $value->format(DateTimeInterface::ATOM);
        }

        if (null === $value || '' === $value) {
            return null;
        }

        try {
            return (new DateTimeImmutable((string) $value))->format(DateTimeInterface::ATOM);
        } catch (\Exception) {
            return null;
        }
    }
}
